@Host=http://127.0.0.1
@Port=3001
@EndpointTemplate = api/empleado


###  1) Validacion de seleccion all - todos los empleados
GET  {{Host}}:{{Port}}/{{EndpointTemplate}}/all
###  2) Validacion de seleccion por ID
GET  {{Host}}:{{Port}}/{{EndpointTemplate}}/select/1


###  3) Validacion de borrado (baja logica del empleado)
DELETE  {{Host}}:{{Port}}/{{EndpointTemplate}}/delete/22

###  4) Creacion de empleado
POST  {{Host}}:{{Port}}/{{EndpointTemplate}}/create
Content-Type: application/json

{
  "nombre": "Leo",
  "apellido": "Messi",
  "dni": "12345678",
  "telefono": "112",
  "email": "leo@example.com",
  "fechaNacimiento": "1990-06-15",
  "fechaIngreso": "2024-03-10",
  "salarioBase": "19000000",
  "genero": "m",
  "area": "Finanzas",
  "puesto": "Contador"
}



###  5) Modificacion de datos del empleado
PATCH   {{Host}}:{{Port}}/{{EndpointTemplate}}/update
Content-Type: application/json

{
  "id": 1,
  "nombre": "Prueba-Editado",
  "apellido": "Empleado-Editado",
  "email": "prueba.editado@example.com",
  "telefono": "11998877",
  "salarioBase": 3500000
}
