@Host=http://127.0.0.1
@Port=3001
@EndpointTempalte = api/empleado

//@mongoId=68f9854ee8539580dad010d6


###  Validacion de seleccion all
GET  {{Host}}:{{Port}}/{{EndpointTempalte}}/all

###  Validacion de seleccion
GET  {{Host}}:{{Port}}/{{EndpointTempalte}}/select/7


###  Validacion de borrado
DELETE  {{Host}}:{{Port}}/{{EndpointTempalte}}/delete/8


###  Creacion de empleado
POST  {{Host}}:{{Port}}/{{EndpointTempalte}}/create
Content-Type: application/json

{
  "nombre": "Lionel",
  "apellido": "Messi",
  "dni": "112131313",
  "telefono": "1133445566",
  "email": "the.goat@example.com",
  "fechaNacimiento": "1990-06-15",
  "fechaIngreso": "2024-03-10",
  "salarioBase": 2500000,
  "areaId": 2,
  "puestoId": 3
}



###  Modificacion de datos del empleado
PATCH   {{Host}}:{{Port}}/{{EndpointTempalte}}/update
Content-Type: application/json

{
  "nombre": "cambio nombre",
  "apellido": "cambio de apellido",
  "id": 10,
  "email": "pruebaDeFranco@example.com"
}